// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeiboFav;

namespace WeiboFav.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20190917011046_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("WeiboFav.Model.Img", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImgPath");

                    b.Property<string>("ImgUrl")
                        .IsRequired();

                    b.Property<int?>("WeiboInfoId");

                    b.HasKey("ImgId");

                    b.HasIndex("WeiboInfoId");

                    b.ToTable("Img");
                });

            modelBuilder.Entity("WeiboFav.Model.WeiboInfo", b =>
                {
                    b.Property<int>("WeiboInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Id")
                        .IsRequired();

                    b.Property<string>("RawHtml")
                        .IsRequired();

                    b.Property<string>("VideoUrl");

                    b.HasKey("WeiboInfoId");

                    b.ToTable("WeiboInfo");
                });

            modelBuilder.Entity("WeiboFav.Model.Img", b =>
                {
                    b.HasOne("WeiboFav.Model.WeiboInfo")
                        .WithMany("ImgUrls")
                        .HasForeignKey("WeiboInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
